version: "3"

services:
  api:
    build: api
    network_mode: "host"
    ports: 
      - "3000:3000"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports: 
      - "9090:9090"
    depends_on:
      - api
      - redis_expo
  
  redis_expo:
    image: oliver006/redis_exporter:latest
    network_mode: "host"
    ports:
      - "9121:9121"
    depends_on:
      - db

